name: Testing atomicswap on ARM emulation

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        arch: [armv6l, armv7l, aarch64]
        include:
          - arch: armv6l
            cpu: arm1176
            base_image: raspios_lite:latest
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:latest
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          commands: |
              sudo apt-get install -y python3-venv python3-pip python3-setuptools
              python3 -m venv test_env
              . test_env/bin/activate
              python -m pip install --upgrade pip
              pip install pytest pylint flake8
              pip install .
              pylint src && pytest test
