name: Automated tests

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.10"]
        include:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pytest
          pip install .
      - name: Lint with flake8
        run: |
          flake8 --count --max-line-length=100 --statistics src
      - name: Lint with pylint
        run: |
          pylint src
      - name: Test with pytest
        run: |
          pytest test

  arm_tests:
    strategy:
      matrix:
        arch: [armv6l, armv7l, aarch64]
        include:
          - arch: armv6l
            cpu: arm1176
            base_image: raspios_lite:latest
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:latest
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          commands: |
              sudo apt-get install -y python3-venv python3-pip python3-setuptools
              python3 -m venv test_env
              . test_env/bin/activate
              python -m pip install --upgrade pip
              pip install pytest pylint flake8
              pip install .
              pylint src && pytest test
