name: Testing atomicswap on ARM emulation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            sudo apt-get install -y python3-venv python3-pip python3-setuptools
            python3 -m venv test_env
            . test_env/bin/activate
            python -m pip install --upgrade pip
            pip install pytest pylint flake8
            pip install .
            pylint src && pytest test
